# Generated by Django 4.1.7 on 2023-03-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catsphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField(null=True)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField()),
                ('photo', models.ImageField(upload_to='image/%Y/%m/%d')),
                ('exist', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
