# Generated by Django 4.1.7 on 2023-03-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catphone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catsphone',
            options={'verbose_name': 'Котофон', 'verbose_name_plural': 'Котофоны'},
        ),
        migrations.AlterField(
            model_name='catsphone',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='catsphone',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='catsphone',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='catsphone',
            name='exist',
            field=models.BooleanField(default=True, verbose_name='В каталоге?'),
        ),
        migrations.AlterField(
            model_name='catsphone',
            name='name',
            field=models.CharField(default='fruit', max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='catsphone',
            name='photo',
            field=models.ImageField(null=True, upload_to='image/%Y/%m/%d', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='catsphone',
            name='price',
            field=models.FloatField(default=10, verbose_name='Цена'),
        ),
    ]
