# Generated by Django 4.1.7 on 2023-03-21 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catphone', '0002_alter_catsphone_options_alter_catsphone_date_create_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название поставщика')),
                ('agent_name', models.CharField(max_length=100, verbose_name='Имя агента поставщика')),
                ('agent_firstname', models.CharField(max_length=100, verbose_name='Фамилия агента поставщика')),
                ('agent_patronymic', models.CharField(max_length=100, verbose_name='Отчество агента поставщика')),
                ('exist', models.BooleanField(default=True, verbose_name='Сотрудничаем?')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='catsphone',
            name='name',
            field=models.CharField(default='котофон', max_length=120, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='catsphone',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catphone.supplier', verbose_name='Поставщик'),
        ),
    ]
