# Generated by Django 4.1.7 on 2023-03-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catphone', '0005_chegue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pos_order',
            old_name='count_fruit',
            new_name='count_product',
        ),
    ]
